server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: ms-comentarios

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db-PetDate}

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db-PetDate}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

contacto:
  destino: petdate8@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
