services:

  petdate-db:
    image: mongo:7.0
    container_name: db-PetDate
    ports:
      - "27017:27017"
    volumes:
      - petdate-data:/data/db
    networks:
      - petdate-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      ms-usuarios:
        condition: service_started
      ms-mascotas:
        condition: service_started
      ms-servicios:
        condition: service_started
      ms-citas-medicas:
        condition: service_started
    restart: unless-stopped
    networks:
      - petdate-network

  ms-usuarios:
    build:
      context: ./ms-usuarios
      dockerfile: Dockerfile
    container_name: petdate-ms-usuarios
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATA_MONGODB_URI: mongodb://petdate-db:27017/db-PetDate
    depends_on:
      petdate-db:
        condition: service_healthy
    networks:
      - petdate-network

  ms-mascotas:
    build:
      context: ./ms-mascotas
      dockerfile: Dockerfile
    container_name: petdate-ms-mascotas
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATA_MONGODB_URI: mongodb://petdate-db:27017/db-PetDate
      MS_USUARIOS_URL: http://ms-usuarios:8081
    depends_on:
      petdate-db:
        condition: service_healthy
      ms-usuarios:
        condition: service_started
    networks:
      - petdate-network

  ms-servicios:
    build:
      context: ./ms-servicios
      dockerfile: Dockerfile
    container_name: petdate-ms-servicios
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATA_MONGODB_URI: mongodb://petdate-db:27017/db-PetDate
    depends_on:
      petdate-db:
        condition: service_healthy
    networks:
      - petdate-network

  ms-citas-medicas:
    build:
      context: ./ms-citas-medicas
      dockerfile: Dockerfile
    container_name: petdate-ms-citas-medicas
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      SPRING_DATA_MONGODB_URI: mongodb://petdate-db:27017/db-PetDate
    depends_on:
      petdate-db:
        condition: service_healthy
      ms-usuarios:
        condition: service_started
      ms-mascotas:
        condition: service_started
    networks:
      - petdate-network

volumes:
  petdate-data:

networks:
  petdate-network:
    driver: bridge