server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-usuarios

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db-PetDate}

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db-PetDate}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:defaultSecretKey}

admin:
  email: ${ADMIN_EMAIL:}
  password: ${ADMIN_PASSWORD:}

ms-mascotas:
  url: ${MS_MASCOTAS_URL:http://localhost:8082}

ms-citas-medicas:
  url: ${MS_CITAS_MEDICAS_URL:http://localhost:8084}

ms-comentarios:
  url: ${MS_COMENTARIOS_URL:http://localhost:8085}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
