# Puerto del servidor
server.port=${SERVER_PORT:8081}

# Nombre de la aplicación
spring.application.name=ms-usuarios

# Configuración de MongoDB Atlas
spring.data.mongodb.uri=mongodb://localhost:27017/db-PetDate

# Configuración de instancia (Eureka)
eureka.instance.hostname=ms-usuarios
eureka.instance.prefer-ip-address=true
